"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("dotenv/config");
const client_1 = require("@prisma/client");
const adapter_pg_1 = require("@prisma/adapter-pg");
const adapter = new adapter_pg_1.PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new client_1.PrismaClient({ adapter });
const data = [
    {
        nombre: "Administrativo Ikea",
        sueldoBase: 539000,
        bonoColacion: 30000,
        bonoLocomocion: 11500,
        bonoAsistencia: 11500,
        bonoNoche: 0,
        otrosBonos: 40000,
        valorHoraExtra: 0,
    },
    {
        nombre: "Coordinador Transporte Ikea Noche",
        sueldoBase: 539000,
        bonoColacion: 70000,
        bonoLocomocion: 35000,
        bonoAsistencia: 31000,
        bonoNoche: 60000,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Jefatura De Area Ikea",
        sueldoBase: 600000,
        bonoColacion: 35000,
        bonoLocomocion: 170000,
        bonoAsistencia: 170000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Operador Maquina III Noche Ikea",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 60000,
        bonoAsistencia: 60000,
        bonoNoche: 50000,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Operario Bodega Ikea",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 5000,
        bonoAsistencia: 5000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Operario Bodega Noche Ikea",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 5000,
        bonoAsistencia: 5000,
        bonoNoche: 50000,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Analista Inventario",
        sueldoBase: 539000,
        bonoColacion: 100000,
        bonoLocomocion: 25000,
        bonoAsistencia: 25000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Analista Inventario Noche",
        sueldoBase: 539000,
        bonoColacion: 100000,
        bonoLocomocion: 20000,
        bonoAsistencia: 20000,
        bonoNoche: 50000,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Certificador Ikea",
        sueldoBase: 539000,
        bonoColacion: 100000,
        bonoLocomocion: 25000,
        bonoAsistencia: 25000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Certificador Noche Ikea",
        sueldoBase: 539000,
        bonoColacion: 100000,
        bonoLocomocion: 20000,
        bonoAsistencia: 20000,
        bonoNoche: 50000,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Operador Maquina III Ikea",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 60000,
        bonoAsistencia: 60000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Operador De Maquina II Ikea",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 60000,
        bonoAsistencia: 60000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Supervisor",
        sueldoBase: 588596,
        bonoColacion: 0,
        bonoLocomocion: 0,
        bonoAsistencia: 100000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Operador Maquina II Noche Ikea",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 60000,
        bonoAsistencia: 60000,
        bonoNoche: 50000,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Operador Maquina Flexy II Noche Ikea",
        sueldoBase: 539000,
        bonoColacion: 40000,
        bonoLocomocion: 60000,
        bonoAsistencia: 60000,
        bonoNoche: 50000,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Administrativo Noche Ikea",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 0,
        bonoAsistencia: 13000,
        bonoNoche: 50000,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Operario Bodega Ikea 2",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 11500,
        bonoAsistencia: 11500,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Operario Bodega Ikea Noche 2",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 13000,
        bonoAsistencia: 0,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Analista Inventario 2",
        sueldoBase: 539000,
        bonoColacion: 60000,
        bonoLocomocion: 0,
        bonoAsistencia: 11500,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Soporte Home Delivery",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 30000,
        bonoAsistencia: 30000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Soporte Desarrollo",
        sueldoBase: 250000,
        bonoColacion: 0,
        bonoLocomocion: 98100,
        bonoAsistencia: 98100,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Ingeniero En Proceso",
        sueldoBase: 550000,
        bonoColacion: 0,
        bonoLocomocion: 210000,
        bonoAsistencia: 210000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Certificador",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 110000,
        bonoAsistencia: 110000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Inventariador Ciclico Dia",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 30000,
        bonoAsistencia: 30000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Inventariados Ciclico Noche",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 30000,
        bonoAsistencia: 30000,
        bonoNoche: 50000,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Analista Coustumer Service",
        sueldoBase: 600000,
        bonoColacion: 0,
        bonoLocomocion: 116500,
        bonoAsistencia: 116500,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Apoyo Prevencion",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 5000,
        bonoAsistencia: 5000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Coordinador De Turno",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 20000,
        bonoAsistencia: 20000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Op Part Time",
        sueldoBase: 222222,
        bonoColacion: 0,
        bonoLocomocion: 71000,
        bonoAsistencia: 710000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Administrativa",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 55000,
        bonoAsistencia: 55000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Tecnico En Prevencion De Riesgo",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 145000,
        bonoAsistencia: 145000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Supervisor De Operaciones Sr",
        sueldoBase: 550000,
        bonoColacion: 0,
        bonoLocomocion: 160000,
        bonoAsistencia: 160000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Tecnico En Prevencion De Riesgo 2",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 85000,
        bonoAsistencia: 85000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Certificador 2",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 58500,
        bonoAsistencia: 58500,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Administrativo Control De Gestion",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 148000,
        bonoAsistencia: 148000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Operativo Apoyo Mantencion",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 45000,
        bonoAsistencia: 45000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Coordinador De Turno 2",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 30000,
        bonoAsistencia: 30000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Asesor Mutual",
        sueldoBase: 3000000,
        bonoColacion: 0,
        bonoLocomocion: 1500000,
        bonoAsistencia: 1500000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Learning Specialist",
        sueldoBase: 750000,
        bonoColacion: 0,
        bonoLocomocion: 320000,
        bonoAsistencia: 320000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Operativo De Embalage",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 0,
        bonoAsistencia: 0,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Analista De Mantencion",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 200000,
        bonoAsistencia: 200000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Operativo De Bodega Apoyo",
        sueldoBase: 750000,
        bonoColacion: 0,
        bonoLocomocion: 0,
        bonoAsistencia: 0,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Asesor De Seguridad Y Prevencion",
        sueldoBase: 2100000,
        bonoColacion: 0,
        bonoLocomocion: 750000,
        bonoAsistencia: 750000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Supervisor 2",
        sueldoBase: 640000,
        bonoColacion: 0,
        bonoLocomocion: 0,
        bonoAsistencia: 0,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Supervisor De Turno 1",
        sueldoBase: 650000,
        bonoColacion: 0,
        bonoLocomocion: 175000,
        bonoAsistencia: 175000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Supervisor De Turno 2",
        sueldoBase: 640000,
        bonoColacion: 0,
        bonoLocomocion: 250000,
        bonoAsistencia: 250000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Bodeguero (Po1) Operario Prevención De Pérdidas",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 5000,
        bonoAsistencia: 5000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Operador De Grúa General (Pc1)",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 60000,
        bonoAsistencia: 60000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Operativo Apoyo De Prevención",
        sueldoBase: 539000,
        bonoColacion: 0,
        bonoLocomocion: 5000,
        bonoAsistencia: 5000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Coordinador De Transporte",
        sueldoBase: 600000,
        bonoColacion: 0,
        bonoLocomocion: 200000,
        bonoAsistencia: 200000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
    {
        nombre: "Coordinador Back Office Logistico",
        sueldoBase: 650000,
        bonoColacion: 0,
        bonoLocomocion: 120000,
        bonoAsistencia: 120000,
        bonoNoche: 0,
        otrosBonos: 0,
        valorHoraExtra: 0,
    },
];
async function main() {
    const empresa = await prisma.empresa.findFirst({
        where: { nombre: { contains: "IKEA", mode: "insensitive" } },
    });
    if (!empresa)
        throw new Error("Empresa IKEA no encontrada");
    const sucursal = await prisma.sucursal.findFirst({
        where: {
            empresaId: empresa.id,
            nombre: { contains: "Reliq", mode: "insensitive" },
        },
    });
    if (!sucursal)
        throw new Error("Sucursal Reliq IKEA no encontrada");
    for (const item of data) {
        let cargo = await prisma.cargo.findFirst({
            where: { nombre: { equals: item.nombre, mode: "insensitive" } },
        });
        if (!cargo) {
            cargo = await prisma.cargo.create({ data: { nombre: item.nombre } });
        }
        await prisma.tarifa.upsert({
            where: {
                empresaId_sucursalId_cargoId: {
                    empresaId: empresa.id,
                    sucursalId: sucursal.id,
                    cargoId: cargo.id,
                },
            },
            update: {
                sueldoBase: item.sueldoBase,
                bonoColacion: item.bonoColacion,
                bonoLocomocion: item.bonoLocomocion,
                bonoAsistencia: item.bonoAsistencia,
                bonoNoche: item.bonoNoche,
                otrosBonos: item.otrosBonos,
                valorHoraExtra: item.valorHoraExtra,
            },
            create: {
                empresaId: empresa.id,
                sucursalId: sucursal.id,
                cargoId: cargo.id,
                sueldoBase: item.sueldoBase,
                bonoColacion: item.bonoColacion,
                bonoLocomocion: item.bonoLocomocion,
                bonoAsistencia: item.bonoAsistencia,
                bonoNoche: item.bonoNoche,
                otrosBonos: item.otrosBonos,
                valorHoraExtra: item.valorHoraExtra,
            },
        });
        console.log(`Insertado/actualizado: ${item.nombre}`);
    }
    console.log("Seed de tarifas Reliq IKEA finalizado correctamente");
}
main()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
